### ISSUE TITLE
Error when starting training

### ISSUE THREAD

**Issue by futurevessel** [smy20011/dreambooth-gui#18]
After running the image and it downloading the necessary files, it reaches 'caching latents: 100%' and then throws the following error:

0%|          | 0/600 [00:00<?, ?it/s]
Steps:   0%|          | 0/600 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/train_dreambooth.py", line 695, in <module>
    main()
  File "/train_dreambooth.py", line 627, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/operations.py", line 507, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/conda/lib/python3.7/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_2d_condition.py", line 299, in forward
    encoder_hidden_states=encoder_hidden_states,
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_blocks.py", line 563, in forward
    hidden_states = attn(hidden_states, context=encoder_hidden_states)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py", line 169, in forward
    hidden_states = block(hidden_states, context=context)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py", line 220, in forward
    hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py", line 350, in forward
    return self.net(hidden_states)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

I'm on Arch Linux, 3060 Nvidia 12GB

**Comment by smy20011** [comment]
For linux, make sure you have correct driver installed. It seems like a CUDA driver. I also use arch linux as well

**Comment by futurevessel** [comment]
Hmmm, I have cuda, cudnn installed, I don't have the python cuda stuff installed though, like python-cuda, python-pytorch-cuda, etc, do you need those ?

This is my first time trying an appimage, I figured it was more like a docker image which pulls in everything it needs. I'm running https://github.com/AbdBarho/stable-diffusion-webui-docker with no problem.

**Comment by smy20011** [comment]
Yeah, it basically a ui for docker. Maybe try to install cuda container
toolkit.

**Comment by futurevessel** [comment]
I already have cuda container toolkit (and its dependencies) installed (from AUR), as I needed them for https://github.com/AbdBarho/stable-diffusion-webui-docker

Those exact packages were: https://aur.archlinux.org/packages/nvidia-container-toolkit, https://aur.archlinux.org/packages/libnvidia-container-tools-bin, https://aur.archlinux.org/packages/libnvidia-container-bin

Sorry to bug you, but I'm scratching my head here, I have no problem running AUTOMATIC1111 or any other Stable Diffusion repo I've tried.

**Comment by futurevessel** [comment]
So I gave it another try, this time I deleted docker image and had it download everything again, and I got a different set of errors, first when launching, it says 'Could not determine the accessibility bus address', but it launches fine and starts downloading after configuring.

Then I get this popup error:
![selection-001](https://user-images.githubusercontent.com/38084366/198343599-970e542e-0b79-4681-8c38-5c7f144b8cee.png)

Followed by this error in the console:

/opt/conda/lib/python3.7/site-packages/bitsandbytes/cuda_setup/paths.py:21: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}
  "WARNING: The following directories listed in your path were found to "
/opt/conda/lib/python3.7/site-packages/bitsandbytes/cuda_setup/paths.py:99: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain libcudart.so as expected! Searching further paths...
  f'{candidate_env_vars["LD_LIBRARY_PATH"]} did not contain '
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /opt/conda/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...

Then caching latents up to 100%, followed by:

0%|          | 0/600 [00:00<?, ?it/s]
Steps:   0%|          | 0/600 [00:00<?, ?it/s]
Steps:   0%|          | 0/600 [00:00<?, ?it/s, loss=0.0597, lr=5e-6]
Steps:   0%|          | 1/600 [00:00<06:12,  1.61it/s, loss=0.0597, lr=5e-6]Traceback (most recent call last):
  File "/train_dreambooth.py", line 695, in <module>
    main()
  File "/train_dreambooth.py", line 645, in main
    accelerator.backward(loss)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/accelerator.py", line 882, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Steps:   0%|          | 1/600 [00:00<07:28,  1.34it/s, loss=0.0597, lr=5e-6]

Anyway, I'd love to get this working, so any hints you might have would be much appreciated.

**Comment by futurevessel** [comment]
Turns out I'm a retard. I thought Class Prompt field was optional, by setting it everything works. Sorry for having wasted your time.
