### ISSUE TITLE
CUDA out of memory on a RTX 3060 12gb GPU

### ISSUE THREAD

**Issue by Baquara** [smy20011/dreambooth-gui#29]
Hello,

Supposedly, this project automatically decide training params that fit the available VRAM.

However, I am getting CUDA out of memory errors on a ~12gb card despite this, when training a model using runwayml/stable-diffusion-v1-5 as the base: 
```

  0%|          | 0/600 [00:00<?, ?it/s]
Steps:   0%|          | 0/600 [00:00<?, ?it/s]
Steps:   0%|          | 0/600 [00:01<?, ?it/s, loss=0.114, lr=1e-5]
Steps:   0%|          | 1/600 [00:01<11:53,  1.19s/it, loss=0.114, lr=1e-5]Traceback (most recent call last):
  File "/train_dreambooth.py", line 695, in <module>
    main()
  File "/train_dreambooth.py", line 645, in main
    accelerator.backward(loss)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/accelerator.py", line 882, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 11.77 GiB total capacity; 8.74 GiB already allocated; 41.12 MiB free; 9.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Steps:   0%|          | 1/600 [00:01<18:06,  1.81s/it, loss=0.114, lr=1e-5]
```

![image](https://user-images.githubusercontent.com/9168959/199356895-8992d6b9-04ad-4778-98cc-d39af1e1f9a4.png)

![image](https://user-images.githubusercontent.com/9168959/199357263-b1335a5f-761d-4318-9d77-2c6e9af29fa6.png)

The default settings for me are:

```

--mixed_precision=fp16
--train_batch_size=1
--gradient_accumulation_steps=1
--use_8bit_adam
```

**Comment by smy20011** [comment]
Wired, try to manually add --gradient_checkpointing=true and rerun

**Comment by Baquara** [comment]
> Wired, try to manually add --gradient_checkpointing=true and rerun

Prior to this post, I had tried this and it worked. But then I restarted the process, it seem it automatically changed the settings to this:


--mixed_precision=fp16
--train_batch_size=2
--gradient_accumulation_steps=1
--gradient_checkpointing
--use_8bit_adam


And it worked.

It seems to change settings around at random...

**Comment by smy20011** [comment]
It will try to detect best training parameter for you based on available vrams. If you start a GPU heavy application after starting the trainer, you may get OOO error.
