### ISSUE TITLE
Possible regression: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasGemmEx

### ISSUE THREAD

**Issue by Baquara** [smy20011/dreambooth-gui#51]
**Describe the bug**
The app works fine for me on version 0.1.6, however, I am facing this issue on the latest versions.

My card is a 3060 with 12gb of VRAM.

**To Reproduce**

0. Use the the 0.1.7 or 0.1.8 releases
1. Select the dataset
2. Use runwayml/stable-diffusion-v1-5
3. 3000 steps
4. 3e-6 LR
5. Use the following settings:
```
--mixed_precision=fp16
--train_batch_size=1
--gradient_accumulation_steps=1
--gradient_checkpointing
--use_8bit_adam
```

**Expected behavior**
The training to start. It works on 0.1.6 but not on the latest versions.

**Logs**
```
 0%|          | 0/3000 [00:00<?, ?it/s]
Steps:   0%|          | 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/train_dreambooth.py", line 695, in <module>
    main()
  File "/train_dreambooth.py", line 627, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/operations.py", line 507, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/conda/lib/python3.7/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_2d_condition.py", line 307, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_blocks.py", line 373, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py", line 169, in forward
    hidden_states = block(hidden_states, context=context)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py", line 220, in forward
    hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py", line 350, in forward
    return self.net(hidden_states)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

Steps:   0%|          | 0/3000 [00:00<?, ?it/s]
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - GPU: RTX 3060 12gb VRAM
 - RAM: 16gb of RAM

**Comment by smy20011** [comment]
Thank you for report! Do you mind install v0.1.6 and rerun it. Just to make sure It's a regression introduced in 0.1.6-0.1.8

**Comment by Baquara** [comment]
> Thank you for report! Do you mind install v0.1.6 and rerun it. Just to make sure It's a regression introduced in 0.1.6-0.1.8
> 
> Do you mind also run a`docker images` in command line?

I am training a model right now on 0.1.6, it is working fine.

As for the second request, here it is:
```

REPOSITORY                             TAG         IMAGE ID       CREATED       SIZE
smy20011/dreambooth                    gpu_debug   3e95c62d9125   10 days ago   15GB
smy20011/dreambooth                    latest      1468ae175524   2 weeks ago   14.9GB
stablediffusion-infinity-sd-infinity   latest      094b1365ee29   6 weeks ago   1.49GB
```

I also updated my system (including CUDA related libs), I will try again with 0.1.8 once I finish the training

**Comment by smy20011** [comment]
I think you can do a `docker pull smy20011/dreambooth:latest` to fix this problem. I accidentally removed docker image update ability in 0.1.6-0.1.8 and you don't have the newest image.

**Comment by Baquara** [comment]
> I think you can do a `docker pull smy20011/dreambooth:latest` to fix this problem. I accidentally removed docker image update ability in 0.1.6-0.1.8 and you don't have the newest image.

I did this, and I can confirm it is now working on the latest version (1.1.8) =)

Thank you!
